/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EscortsRouteImport } from './routes/escorts'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportRouteImport } from './routes/report'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesFirstTimeBookingRouteImport } from './routes/guides/first-time-booking'
import { Route as GuidesIncallVsOutcallRouteImport } from './routes/guides/incall-vs-outcall'
import { Route as LocationsLocationIdRouteImport } from './routes/locations/$locationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EscortsRoute = EscortsRouteImport.update({
  id: '/escorts',
  path: '/escorts',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFirstTimeBookingRoute = GuidesFirstTimeBookingRouteImport.update({
  id: '/guides/first-time-booking',
  path: '/guides/first-time-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIncallVsOutcallRoute = GuidesIncallVsOutcallRouteImport.update({
  id: '/guides/incall-vs-outcall',
  path: '/guides/incall-vs-outcall',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIdRoute = LocationsLocationIdRouteImport.update({
  id: '/locations/$locationId',
  path: '/locations/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/areas': typeof AreasRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/escorts': typeof EscortsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/why-us': typeof WhyUsRoute
  '/guides/first-time-booking': typeof GuidesFirstTimeBookingRoute
  '/guides/incall-vs-outcall': typeof GuidesIncallVsOutcallRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/areas': typeof AreasRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/escorts': typeof EscortsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/why-us': typeof WhyUsRoute
  '/guides/first-time-booking': typeof GuidesFirstTimeBookingRoute
  '/guides/incall-vs-outcall': typeof GuidesIncallVsOutcallRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/areas': typeof AreasRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/escorts': typeof EscortsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/why-us': typeof WhyUsRoute
  '/guides/first-time-booking': typeof GuidesFirstTimeBookingRoute
  '/guides/incall-vs-outcall': typeof GuidesIncallVsOutcallRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/areas'
    | '/book'
    | '/contact'
    | '/escorts'
    | '/help'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/report'
    | '/why-us'
    | '/guides/first-time-booking'
    | '/guides/incall-vs-outcall'
    | '/locations/$locationId'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/areas'
    | '/book'
    | '/contact'
    | '/escorts'
    | '/help'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/report'
    | '/why-us'
    | '/guides/first-time-booking'
    | '/guides/incall-vs-outcall'
    | '/locations/$locationId'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/areas'
    | '/book'
    | '/contact'
    | '/escorts'
    | '/help'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/report'
    | '/why-us'
    | '/guides/first-time-booking'
    | '/guides/incall-vs-outcall'
    | '/locations/$locationId'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AreasRoute: typeof AreasRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  EscortsRoute: typeof EscortsRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  WhyUsRoute: typeof WhyUsRoute
  GuidesFirstTimeBookingRoute: typeof GuidesFirstTimeBookingRoute
  GuidesIncallVsOutcallRoute: typeof GuidesIncallVsOutcallRoute
  LocationsLocationIdRoute: typeof LocationsLocationIdRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escorts': {
      id: '/escorts'
      path: '/escorts'
      fullPath: '/escorts'
      preLoaderRoute: typeof EscortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/first-time-booking': {
      id: '/guides/first-time-booking'
      path: '/guides/first-time-booking'
      fullPath: '/guides/first-time-booking'
      preLoaderRoute: typeof GuidesFirstTimeBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/incall-vs-outcall': {
      id: '/guides/incall-vs-outcall'
      path: '/guides/incall-vs-outcall'
      fullPath: '/guides/incall-vs-outcall'
      preLoaderRoute: typeof GuidesIncallVsOutcallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$locationId': {
      id: '/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof LocationsLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AreasRoute: AreasRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  EscortsRoute: EscortsRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  WhyUsRoute: WhyUsRoute,
  GuidesFirstTimeBookingRoute: GuidesFirstTimeBookingRoute,
  GuidesIncallVsOutcallRoute: GuidesIncallVsOutcallRoute,
  LocationsLocationIdRoute: LocationsLocationIdRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
